fix(build,juel): Declare jakarta-el with runtime scope
In module juel the dependency is configured with default scope (which is compile). Modules depending on it, which is especially the ProcessEngine through JuelExpressionManager, will need JakartaEL in their runtime.

This could cause NoClassDefFoundError for JakartaEL classes at runtime.

fixes #242